{% set name = "openphase" %}
{% set version = "2.1" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://github.com/ICAMS/OpenPhase/archive/Release/{{ version }}.tar.gz
  sha256: 36b435e6207cb35595ff9578fb5bccba8081d81cb7be00ca6233c81b9605cc47

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - cmake
    - make  # [unix]
  host:
    - fftw
  run:
    - fftw

test:
  commands:
    # adapt to an actual installed binary or library
    - test -f $PREFIX/bin/openphase || test -f $PREFIX/lib/libOpenPhase.so  # [unix]

about:
  home: https://github.com/ICAMS/OpenPhase
  summary: "High-performance phase-field simulation framework for materials science"
  description: |
    OpenPhase is a modular, high-performance phase-field simulation framework
    for modeling microstructure evolution in materials science.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - samwaseda
